#!/usr/bin/env python3
"""Report substantive differences between the book poems and sculpture prompts.

  python pipeline/diff_prompts.py        # writes PROMPT_DIFFS.md at repo root

For every curated sonnet manifest, each image line's prompt text (the use line
the image was generated from) is diffed word-by-word against its aligned poem
lines. Differences are classified:

  symbolizing — insertions from the known abstraction vocabulary
                ("conceptual", "miniature abstract", ...): systematic, not
                substantive, but listed for the record
  anchor      — words repeated from an earlier group to give the prompt
                context ("desire", "I alone")
  substantive — everything else: word swaps, paraphrases, additions

Regenerate after ingesting or re-styling a sonnet, and commit the result.
"""
import difflib
import json
import re
from pathlib import Path

ROOT = Path(__file__).parent.parent
OUT = ROOT / "PROMPT_DIFFS.md"

# from the "basic lines" cell of the FLUX Colab
SYMBOLIZING = {"figurative", "non-representational", "simplified", "virtual",
               "exaggerated", "emblematic", "symoblic", "symbolic", "abstract",
               "stylized", "metaphorical", "conceptual", "caricature", "of",
               "minimalist", "implied", "representative", "miniature"}


def toks(s):
    return re.findall(r"[\w']+", s.lower())


def classify(kind, poem_words, prompt_words, earlier_words):
    if kind == "insert" and all(w in SYMBOLIZING for w in prompt_words):
        return "symbolizing"
    if kind == "insert" and all(w in earlier_words for w in prompt_words):
        return "anchor"
    return "substantive"


def diff_line(poem_lines, prompt, earlier_words):
    a = [t for ln in poem_lines for t in toks(ln)]
    b = toks(prompt)
    out = []
    for op, a0, a1, b0, b1 in difflib.SequenceMatcher(None, a, b).get_opcodes():
        if op == "equal":
            continue
        kind = {"insert": "insert", "delete": "dropped", "replace": "changed"}[op]
        label = classify("insert" if op == "insert" else op,
                         a[a0:a1], b[b0:b1], earlier_words)
        if op == "insert":
            out.append((label, f'prompt adds "{" ".join(b[b0:b1])}"'))
        elif op == "delete":
            out.append(("substantive", f'prompt drops "{" ".join(a[a0:a1])}"'))
        else:
            out.append(("substantive",
                        f'"{" ".join(a[a0:a1])}" → "{" ".join(b[b0:b1])}"'))
    return out


def main():
    sections = []
    total_subst = 0
    for manifest_path in sorted((ROOT / "content" / "sonnets").glob("*/manifest.json")):
        m = json.loads(manifest_path.read_text())
        rows = []
        nonblank = [ln for ln in m.get("transbliteration", []) if ln.strip()]
        for line in m.get("lines", []):
            poem_lines, prompt = line.get("poem_lines"), line.get("text", "")
            if not poem_lines or not prompt:
                continue
            # anchors may echo any earlier line of the poem, imaged or not
            try:
                start = nonblank.index(poem_lines[0])
            except ValueError:
                start = 0
            earlier_words = set(t for ln in nonblank[:start] for t in toks(ln))
            diffs = diff_line(poem_lines, prompt, earlier_words)
            if diffs:
                poem_flat = " / ".join(ln.strip() for ln in poem_lines)
                rows.append((line["n"], poem_flat, prompt, diffs))
                total_subst += sum(1 for label, _ in diffs if label == "substantive")
        if rows:
            sections.append((m, rows))

    lines = ["# Book ↔ Sculpture-Prompt Differences", "",
             "Auto-generated by `pipeline/diff_prompts.py` — do not edit by hand.",
             "The prompts intentionally abstract the poems (symbolizing words,",
             "context anchors); **substantive** entries are real divergences.", ""]
    for m, rows in sections:
        lines.append(f"## Sonnet {m['roman']} — Transbliterated ({m['seq']:03d}), "
                     f"run `{m.get('run', '?')}`")
        lines.append("")
        for n, poem_flat, prompt, diffs in rows:
            lines.append(f"### image line {n}")
            lines.append(f"- poem: *{poem_flat}*")
            lines.append(f"- prompt: *{prompt}*")
            for label, desc in diffs:
                mark = "**substantive**" if label == "substantive" else label
                lines.append(f"  - {mark}: {desc}")
            lines.append("")
    lines.append(f"---\n{total_subst} substantive difference(s) across "
                 f"{len(sections)} sonnet(s).")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.name}: {total_subst} substantive difference(s)")


if __name__ == "__main__":
    main()
